GO
CREATE TABLE Currencies
(
	Id TINYINT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(10) NULL,
	ShortName NVARCHAR(5) NOT NULL,

	CONSTRAINT primaryCurrencyKey PRIMARY KEY (Id)
)

GO
CREATE TABLE Clients
(
	Id INT IDENTITY(1,1) NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Patronymic NVARCHAR(100) NOT NULL,

	CONSTRAINT primaryClientKey PRIMARY KEY (Id)
)

GO
CREATE TABLE CreditCards
(
	Id INT IDENTITY(1,1) NOT NULL,
	Number NVARCHAR(50) NOT NULL,
	Cash DECIMAL(10,10) NOT NULL,
	CurrensyId TINYINT NOT NULL,
	UserId INT NOT NULL,

	CONSTRAINT primaryCreditCardKey PRIMARY KEY (Id),
	CONSTRAINT foreignCreditCardsToCurrenciesKey FOREIGN KEY (CurrensyId)
		REFERENCES Currencies (Id),
	CONSTRAINT foreignCreditCardsToClientsKey FOREIGN KEY (UserId)
		REFERENCES Clients (Id)
)